<?php
	$page_data = [
		"hero_viewer"=>[
			"title"=>"Galería para artistas merideños",
			"message"=>"Reconocidos como el destino preferido para el turismo andino, ofrecemos la mejor experiencia para disfrutar la ciudad turística por excelencia",
			"action_button_message" => "Contáctanos",
			"action_button_href" => "contacto",

			"image"=>"art_hero.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"",
			"image_left"=>"-2dvw",
			"image_height"=>"117%",
		],
		
		"heading_1"=>[
			"message"=>"Arte en cada momento de tu estadía"
		],
		
		"selected_work_viewer"=>[
			"title"=>"Arte merideño",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"image"=>"i2_escritorio.webp",
			"action_button_message" => "Reservar",
			"action_button_href" => "contacto",

			"image"=>"art_2.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"4dvw",
			"image_left"=>"-2dvw",
			"image_height"=>"400%",
		],
		"work_1"=>[
			"title"=>"obra 1",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_1.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_2"=>[
			"title"=>"obra 2",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_2.webp",
			"image_top"=>"0.5dvw",
			"image_left"=>"-.5dvw",
			"image_height"=>"300%",
		],
		"work_3"=>[
			"title"=>"obra 3",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_3.webp",
			"image_top"=>"10dvw",
			"image_left"=>"-2.5dvw",
			"image_height"=>"300%",
		],
		"work_4"=>[
			"title"=>"obra 4",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_4.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_5"=>[
			"title"=>"obra 5",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_5.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_6"=>[
			"title"=>"obra 6",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_6.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_7"=>[
			"title"=>"obra 7",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_7.webp",
			"image_top"=>"2dvw",
			"image_left"=>"2dvw",
			"image_height"=>"300%",
		],
		"work_8"=>[
			"title"=>"obra 8",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_8.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_9"=>[
			"title"=>"obra 9",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_9.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_10"=>[
			"title"=>"obra 10",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_10.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_11"=>[
			"title"=>"obra 11",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_11.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_12"=>[
			"title"=>"obra 12",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_12.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_13"=>[
			"title"=>"obra 13",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_13.webp",
			"image_top"=>"14dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_14"=>[
			"title"=>"obra 14",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_16.webp",
			"image_top"=>"0dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		"work_15"=>[
			"title"=>"obra 15",
			"description"=>"Obra de un talentoso artista merideño, realizada con óleo sobre lienzo. Actualmente ilumina los espacios del hotel aportando interés visual y estimulos intelectuales para nuestros huéspedes",
			"author"=>"artista merideño",
			"technique"=>"óleo sobre lienzo",
			"date"=>"12/03/2021",
			"image"=>"art_18.webp",
			"image_top"=>"2dvw",
			"image_left"=>"0dvw",
			"image_height"=>"300%",
		],
		

		
		"heading_2"=>[
			"message"=>"Conoce nuestra galería"
		],
		
		"gallery_strip_1"=>[
			"title"=>"La habitación perfecta",
			"message"=>"12 tipos de habitaciones distribuídas en 100 unidades de hospedaje y un excelente servicio para cada una de ellas",
			"action_button_message" => "Explorar",
			"action_button_href" => "habitaciones",

			"image"=>"cabana_2_3840x2160.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"0dvw",
			"image_left"=>".5dvw",
			"image_height"=>"115%",			
		],
		
		"gallery_strip_2"=>[
			"title"=>"La habitación perfecta",
			"message"=>"12 tipos de habitaciones distribuídas en 100 unidades de hospedaje y un excelente servicio para cada una de ellas",
			"action_button_message" => "Explorar",
			"action_button_href" => "habitaciones",

			"image"=>"cabana_2_3840x2160.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"0dvw",
			"image_left"=>".5dvw",
			"image_height"=>"115%",			
		],
		
		"gallery_strip_3"=>[
			"title"=>"La habitación perfecta",
			"message"=>"12 tipos de habitaciones distribuídas en 100 unidades de hospedaje y un excelente servicio para cada una de ellas",
			"action_button_message" => "Explorar",
			"action_button_href" => "habitaciones",

			"image"=>"cabana_2_3840x2160.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"0dvw",
			"image_left"=>".5dvw",
			"image_height"=>"115%",			
		],
		
		"gallery_strip_4"=>[
			"title"=>"La habitación perfecta",
			"message"=>"12 tipos de habitaciones distribuídas en 100 unidades de hospedaje y un excelente servicio para cada una de ellas",
			"action_button_message" => "Explorar",
			"action_button_href" => "habitaciones",

			"image"=>"cabana_2_3840x2160.webp",
			"images_folder_path_from_root_folder"=>"_/media/image/",
			"logo"=>"belensate_icon_stars.webp",
			"image_top"=>"0dvw",
			"image_left"=>".5dvw",
			"image_height"=>"115%",			
		],
		
		"heading_3"=>[
			"message"=>"Preparamos tu estadía"
		],
	];
?>